name: WBLite
author: [white_cola,lvxinlei,Chloe__owo]
version: 1.0
main: top.whitecola.wblite.WBLite
depend: [MiraiBukkit,WhiteList]
commands: 
  wb: 
   usage: /wb <childCmd> [args]...
permissions: 
  wb.reload: 
   default: op
  wb.sendmsg: 
   default: op 
    